layout_spectrum: 0.5174895846722002
typography_spectrum: 0.7348529384865213
color:
  lightness: 0.25127024909407636
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  saturation: 0.9657963618114221
  brandStrength: 0.46742513545106473
  rhythmicContrast: 0.3683545599395575
name: The Yogi Cave
analytics: {}
content_rating:
  adult: false
github: true
opengraph: {}
title: The Inner Path to Enlightenment
author:
  url: 'http://www.theyogicave.com'
content: []
