layout_spectrum: 0.42520008144494476
typography_spectrum: 0.6004087149737274
color:
  lightness: 0.9940756528390258
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  saturation: 0.06280702748050046
  brandStrength: 0.35964181818123353
  rhythmicContrast: 0.6711601933660816
name: The Yogi Cave
analytics: {}
content_rating:
  adult: false
github: true
opengraph: {}
title: The Inner Path to Enlightenment
author:
  url: 'http://www.theyogicave.com'
content: []
